name: KASM

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Download ngrok
        run: |
          cd ~
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null &&
              echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list &&
              sudo apt update && sudo apt install ngrok
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      
      - name: Increase SWAP
        run: |
          sudo dd if=/dev/zero bs=1M count=1024 of=/mnt/1GiB.swap
          sudo chmod 600 /mnt/1GiB.swap
          sudo mkswap /mnt/1GiB.swap
          sudo swapon /mnt/1GiB.swap
          cat /proc/swaps
      - name: Run install
        run: |
          cd /tmp
          wget https://kasm-static-content.s3.amazonaws.com/kasm_release_1.10.0.238225.tar.gz
          tar -xf kasm_release*.tar.gz
          rm -rf kasm_release/conf
          cp -r conf kasm_release
          rm -rf kasm_release/install.sh
          cp install.sh kasm_release
          echo y | sudo bash kasm_release/install.sh -L 8443
          ngrok http -region ap --log=stdout https://localhost:8443